<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.22" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CapG.OMS.Exceptions\CapG.OMS.Exceptions.csproj" />
    <ProjectReference Include="..\CapG.OMS.Models\CapG.OMS.Models.csproj" />
  </ItemGroup>

</Project>
