<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.22" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.22" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.22">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="3.1.22" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.22" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="6.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Capgemini.OIBS.Exceptions\Capgemini.OIBS.Exceptions.csproj" />
    <ProjectReference Include="..\Capgemini.OIBS.Models\Capgemini.OIBS.Models.csproj" />
    <ProjectReference Include="..\Capgemini.OIBS.Repositories\Capgemini.OIBS.Repositories.csproj" />
  </ItemGroup>


</Project>
