<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.EventGrid" Version="4.8.2" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CapG.MTBS.Models\CapG.MTBS.Models.csproj" />
    <ProjectReference Include="..\MtbsException\CapG.MTBS.Exceptions.csproj" />
  </ItemGroup>

</Project>
